// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWsQoI6sDIcmNlTw4xmKl3C81vbLC5-SU',
    appId: '1:495185543742:web:bf5354d3cbc2c1724f476f',
    messagingSenderId: '495185543742',
    projectId: 'fir-learnings-40407',
    authDomain: 'fir-learnings-40407.firebaseapp.com',
    storageBucket: 'fir-learnings-40407.firebasestorage.app',
    measurementId: 'G-NS2XT4MF56',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDlVoRa1X_vzdnJ-eZn-2WPU2-lPyyGmiI',
    appId: '1:495185543742:android:b21a2e7d8d0689944f476f',
    messagingSenderId: '495185543742',
    projectId: 'fir-learnings-40407',
    storageBucket: 'fir-learnings-40407.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwgo0fSrgH0UaMhZSvrVsXJU0MXE_iR8U',
    appId: '1:495185543742:ios:163407a585437a204f476f',
    messagingSenderId: '495185543742',
    projectId: 'fir-learnings-40407',
    storageBucket: 'fir-learnings-40407.firebasestorage.app',
    androidClientId: '495185543742-blet4mqiske719tbkv4svb4i4oubgla3.apps.googleusercontent.com',
    iosClientId: '495185543742-gjkjqpehj56nrc6i2piure1cp4a71ucc.apps.googleusercontent.com',
    iosBundleId: 'com.example.taskManager',
  );
}
